{% set name = "fsleyes-widgets" %}
{% set version = "0.8.0" %}
{% set sha256 = "67671479e5b8a7898c2b803149268452f2e3062af0d2549b1656aaa15c0f39bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy 1.*
    - matplotlib >=1.5
    - six 1.*
    - wxpython >=3.0.2.0

test:
  source_files:
    - tests
  requires:
    - mock 2.*
    - coverage 4.*
    - pytest 3.*
    - pytest-cov 2.*
  commands:
    - xvfb-run -s "-screen 0 640x480x24" pytest -v --cov=fsleyes_widgets

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A collection of wxPython widgets used by FSLeyes'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
