{% set name = "fsleyes-widgets" %}
{% set version = "0.11.1" %}
{% set sha256 = "0d93de970efdb24d6de9b7b8302efde5e533f9b7ba8b70c6c8e6d5d033da3f99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - matplotlib-base >=1.5
    - wxpython >=3.0.2.0

test:
  source_files:
    - tests
  requires:
    - coverage
    - mock
    - pytest
    - pytest-cov
  commands:
    - xvfb-run -s "-screen 0 1200x800x24" pytest -v --cov=fsleyes_widgets -m "not dodgy"

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of wxPython widgets used by FSLeyes
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
