{% set name = "fsleyes-widgets" %}
{% set pypi_name = "fsleyes_widgets" %}
{% set version = "0.14.6" %}
{% set sha256 = "6aedb917360101b11b63c13afe57051e6ea5eaf110af934a16302dcef3dabaa5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - matplotlib-base >=3.5
    - wxpython >=3.0.2.0

test:
  source_files:
    - pyproject.toml
    - fsleyes_widgets/tests
  requires:
    - coverage
    - pytest
    - pytest-cov
  commands:
    - xvfb-run -s "-screen 0 1200x800x24" pytest -v -m "not dodgy" fsleyes_widgets/tests/

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of wxPython widgets used by FSLeyes
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
