{% set name = "fsleyes-widgets" %}
{% set pypi_name = "fsleyes_widgets" %}
{% set version = "0.15.2" %}
{% set sha256 = "efcd1f50911972141cd4f127182cde1271a571c4df3a2caa4e66d87a6fb87d7d" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base >=3.5
    - wxpython >=3.0.2.0

test:
  source_files:
    - pyproject.toml
    - fsleyes_widgets/tests
  requires:
    - coverage
    - pytest
    - pytest-cov
    - python {{ python_min }}
  commands:
    - xvfb-run -s "-screen 0 1200x800x24" pytest -v -m "not dodgy" fsleyes_widgets/tests/

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of wxPython widgets used by FSLeyes
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
