{% set name = "fsleyes-widgets" %}
{% set version = "0.6.3" %}
{% set sha256 = "fe1151927446474b305a4a29d648b0db45f5054a351581273fbe5918e3b76cf6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - sphinx 1.6.*
    - sphinx_rtd_theme 0.*
    - mock 2.*
    - coverage 4.*
    - pytest 3.*
    - pytest-cov 2.*
    - pytest-runner >=2.*,<=4.*
  run:
    - python
    - deprecation >=1.*,<=2.*
    - numpy 1.*
    - matplotlib >=1.5,<3
    - six 1.*
    - wxpython <4.1


test:
  commands:
    - python -c "import fsleyes_widgets"


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A collection of wxPython widgets used by FSLeyes'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
