{% set name = "fsleyes-widgets" %}
{% set version = "0.6.5" %}
{% set sha256 = "fc4088d0e31fd7fbbe9797b2fce6649ce2e91fb55cde10424b54e82c1f519fec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - deprecation >=1.*,<=2.*
    - numpy 1.*
    - matplotlib >=1.5,<3
    - six 1.*
    - wxpython <4.1

test:
  source_files:
    - tests
  requires:
    - mock 2.*
    - coverage 4.*
    - pytest 3.*
    - pytest-cov 2.*
  commands:
    -  xvfb-run -s "-screen 0 640x480x24" pytest -v --cov=fsleyes_widgets
  imports:
    - fsleyes_widgets.autotextctrl
    - fsleyes_widgets.bitmapradio
    - fsleyes_widgets.bitmaptoggle
    - fsleyes_widgets.colourbutton
    - fsleyes_widgets.dialog
    - fsleyes_widgets.elistbox
    - fsleyes_widgets.floatslider
    - fsleyes_widgets.floatspin
    - fsleyes_widgets.imagepanel
    - fsleyes_widgets.notebook
    - fsleyes_widgets.numberdialog
    - fsleyes_widgets.placeholder_textctrl
    - fsleyes_widgets.rangeslider
    - fsleyes_widgets.textpanel
    - fsleyes_widgets.texttag
    - fsleyes_widgets.togglepanel
    - fsleyes_widgets.widgetgrid
    - fsleyes_widgets.widgetlist
    - fsleyes_widgets.utils.colourbarbitmap
    - fsleyes_widgets.utils.layout
    - fsleyes_widgets.utils.progress
    - fsleyes_widgets.utils.runwindow
    - fsleyes_widgets.utils.status
    - fsleyes_widgets.utils.textbitmap
    - fsleyes_widgets.utils.typedict
    - fsleyes_widgets.utils.webpage

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A collection of wxPython widgets used by FSLeyes'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
