{% set name = "fsleyes-widgets" %}
{% set version = "0.8.1" %}
{% set sha256 = "0066ef2ebbad3c1eab25e75fdb9787faaa5dbd147c62533a55e1784eb049d95e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy 1.*
    - matplotlib >=1.5
    - six 1.*
    - wxpython >=3.0.2.0

test:
  source_files:
    - tests
  requires:
    - mock 2.*
    - coverage 4.*
    - pytest 3.*
    - pytest-cov 2.*
  commands:
    - xvfb-run -s "-screen 0 1200x800x24" pytest -v --cov=fsleyes_widgets

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A collection of wxPython widgets used by FSLeyes'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsleyes/widgets/

extra:
  recipe-maintainers:
    - pauldmccarthy
