travis:
  secure:
    BINSTAR_TOKEN: MyCTCRrmr3XSFSSKbrUendQvUMmt28cYnsYY9hrcI9jh+SZU4svnpuXbCeE57QqrFqJX7LA1K7Pbclxv/e6CbRYKtvfj96w+aml6VK0MxEvCMV/xzyBT4j0NlsjyuA2mbYheOoACA1hdO2+ASKWkHsnMcCwgiHjv/+1/EyQp7nxoO+MORQlPZaqdu40XX+zuN+UXKS8+my90sa86sxL7b59SHKz07mhbmHHBQsrc2xXgrWbH8B0fM6BD97szVunxIlbojX73h//dwJ3F0q6ZdmfgUiqvx6c2u4MO4sJsNLAue9DSBs4qAjdF3/wvlwv6sndt94/Eti3D5lywsQg3duLznwFYMIWYTzqRz3WKBOJWISqsTq4WL8GrBEo6+Y6JAXaEkKkL8rcH2zdmKasNjkrqnPhY3FclVpavTTLjYLTTkl4oo0V0NpjqUcaJRGFhZ8jX7lLpEEbVbVgQYN1gGGMwH4fDgUSFogeg8Dr2XBp7pUrccBfrSCUKQyRymG6iHDb2Vg7JonaQTmAvoLG/DQ+CETs2X4k995jJtZn9kXLEZ32uReI95VKeMeaLH7DY18+XKAGorfPr7We7+pIpKic1L3Q9hZe+qXXP1C5WB3th/yG/0zJXMR2s63nVxMj1UronNGcI7laKEgxwYFiVvqq6agQ+7+ghziXDQSd1XOo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
